# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    #password encoder
    encoders:
        AppBundle\Entity\User: bcrypt
    
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        #To remove error: There is no user provider for user AppBundle\Entity\User
        #Add following two lines and delete in_memory stuff
        our_users:
            entity: { class: AppBundle\Entity\User, property: email }
        #in_memory:
        #    memory: ~

    firewalls:
        #Disables authentication for assets and the profiler, 
        # adapt it according to your needs
        #Your firewall is your authentication system: 
        # it's like the security desk you pass when going into a building. 
        # Now, there's always only one firewall that's active on any request. 
        # You see, if you go to a URL that starts with: 
        # /_profiler, /_wdt or /css, 
        # you hit the dev firewall only.
        # This basically turns security off: it's like sneaking through 
        # the side door of a building that has no security desk. 
        # This is here to prevent us from getting over-excited with security 
        # and accidentally securing our debugging tools.
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        #In reality, every real request will activate the main firewall.
        # Because it has no pattern key, it matches all URLs.
        # Our job is to activate different ways 
        # to authenticate under this one firewall. 
        # We might allow the user to authenticate via 
        # a form login, HTTP basic, an API token, Facebook login 
        # or all of these. 
        #We won't use form_login: 
        # You can add a key called form_login under the firewall. 
        # Then, everything just magically works.
        # It's really cool because it's quick to set up! 
        # But it's super magical and hard to extend and control.
        #We use as system called GUARD:
        # It is more work to setup, 
        # but you'll have control over everything from day 1.
        # The first step is always to create an authenticator class:
        # LoginFormAuthenticator.php
        main:
            anonymous: ~           
            guard:
                # activate the authenticator
                authenticators:
                    - app.security.login_form_authenticator
            
            #activate logout
            logout:
                path: /logout
                       
            #Impersonation
            #The worst is when a user reports a bug in their account... 
            #which would be really easy to verify and debug... 
            #if only we could log and see what they're seeing.
            #We need to be able switch to that user's account: 
            #we need to impersonate them.
            #On any URL, you can add 
            #?_switch_user= 
            #and then the username of whoever you want to log in as.
            #We can't just let anybody do this impersonation trick. 
            #Internally, this feature checks for a very specific role called 
            #ROLE_ALLOWED_TO_SWITCH
            #by adding 
            #?_switch_user=_exit 
            #to any URL. 
            #That's it! We're back as our original user.
            switch_user: ~
            
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    
    #There are 2 main ways to deny access, 
    #and the simplest is right inside of security.yml. 
    #It's called "access control".
    #That path is a regular expression. 
    #So, if anyone goes to a URL that starts with /admin, 
    #the system will kick them out unless they have ROLE_USER
    #The only rule about roles is that roles must start with ROLE_
    #I do use access controls to lock down big sections, 
    #but, mostly, I handle authorization inside my controllers.
    #For a role ROLE_XYZ use either annotations:
    # - @Security("is_granted('ROLE_XYZ')")
    #Or this line inside Action()
    # - $this->denyAccessUnlessGranted('ROLE_XYZ');
    #to lock down an entire controller 
    #put the @Security() line above the controller
    access_control:
        #- { path: ^/admin, roles: ROLE_USER }
    
    #role hierachy
    #The strategy is this: first: 
    #lock down different sections using role names 
    #that describe what it's protecting
    #- like ROLE_OCTOPUS_PHOTO_MANAGE. 
    #Second, in security.yml, create group-based roles here
    #- like ROLE_MARINE_BIOLOGIST or ROLE_MANAGEMENT - 
    #and assign each the permissions they should have. 
    #With this setup, you should be able 
    #to give most users just one role in the database.
    role_hierarchy:
        #if anybody has ROLE_ADMIN, 
        #automatically give them ROLE_MANAGE_GENUS (GenusAdminController.php)
        #ROLE_ALLOWED_TO_SWITCH 
        #is a special role which allows impersonation
        ROLE_ADMIN: [ROLE_MANAGE_GENUS, ROLE_ALLOWED_TO_SWITCH]