# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

#MarkdownTransformer class
# To add a new service to the container, 
# you basically need to teach the container 
# how to instantiate your object.
# 1. Give your new service a nickname: 
#    This can be anything: we'll use it later to fetch the service
#    How about: app.markdown_transformer
# 2. Our own new service class
# 3. The arguments to pass to the constructor. 
#    The @ is special: it says:
#    Don't pass the string markdown.parser, 
#    pass the service markdown.parser
# -> A new service has been born. Go look for it:
#    - php bin/console debug:container markdown
# This configuration causes Symfony to write 
# plain PHP code that creates our service objects in:
#    var/cache/dev/appDevDebugProjectContainer.php
# Ultimately, when we ask for the 
#    app.markdown_transformer service, 
#    the protected function getApp_MarkdownTransformerService() 
#    method is called in:
#    var/cache/dev/appDevDebugProjectContainer.php
    app.markdown_transformer:
        class: AppBundle\Service\MarkdownTransformer
        arguments: ['@markdown.parser', '@doctrine_cache.providers.my_markdown_cache']
        
# Symfony dependency injection tags:
# Tags are the way to hook your services into different parts of the core system. 
# When Symfony creates the twig service, it looks for all services 
# in the container that are tagged with twig.extension. 
# It then configures these as extensions on twig.
# With autowire: true, Symfony reads the type-hints for each 
# constructor argument and tries to automatically find the correct 
# service to pass to you
#
    app.markdown_extension:
        class: AppBundle\Twig\MarkdownExtension
        tags:
            - { name: twig.extension }
        #arguments: ['@app.markdown_transformer']
        autowire: true
        
# Register the authenticator as a service
# We can autowire the arguments because 
# we type-hinted all the constructor arguments.
# Name: app.security.login_form_authenticator
    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true
        
# Registering the Subscriber as a Service
# To tell Doctrine about our event subscriber, 
# we'll add a tag. 
# This is something we talked about in our services course: 
# it's a way to tell the system 
# that your service should be used for some special purpose.
# Before creating or updating any entities, 
# Doctrine will call our listener
    app.doctrine.hash_password_listener:
        class: AppBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }